import { Link } from 'react-router-dom';

import { AppHeader } from '../components/AppHeader';
import { Card } from '../components/ui';
import { useAuthStore } from '../store';

export function LegalPage({ kind }: { kind: 'terms' | 'privacy' }): React.JSX.Element {
  const user = useAuthStore((state) => state.user);
  const privacy = kind === 'privacy';
  return <main className="min-h-screen bg-[#fff1d6] text-ilarica-ink">{user && <AppHeader />}<div className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><Link to={user ? '/perfil' : '/cadastro'} className="text-sm font-bold text-ilarica-orange">← Voltar</Link><h1 className="mt-5 font-display text-3xl font-extrabold text-[#7a1e1e]">{privacy ? 'Política de Privacidade' : 'Termos de Uso'}</h1><p className="mt-2 text-sm text-ilarica-muted">Versão do piloto controlado — atualizada em agosto de 2026.</p><Card className="mt-7 space-y-6 border-0 p-6 leading-relaxed shadow-none sm:p-9">{privacy ? <><section><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Dados utilizados</h2><p className="mt-2">Utilizamos nome, e-mail institucional e WhatsApp para autenticação, comunicação operacional e execução dos pedidos.</p></section><section><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Finalidade e compartilhamento</h2><p className="mt-2">Dados mínimos do pedido são compartilhados somente com a cantina responsável. Não comercializamos dados pessoais.</p></section><section><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Seus direitos</h2><p className="mt-2">Você pode solicitar acesso, correção ou exclusão de dados pelo canal de suporte, observadas as retenções necessárias para auditoria de pedidos.</p></section></> : <><section><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Uso do serviço</h2><p className="mt-2">O iLarica conecta clientes e cantinas no ecossistema UFCA. O usuário deve fornecer informações corretas e preservar suas credenciais.</p></section><section><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Pedidos e retirada</h2><p className="mt-2">Preços e disponibilidade são confirmados pelo servidor. O PIN de retirada é pessoal e deve ser apresentado apenas no balcão da cantina.</p></section><section><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Piloto</h2><p className="mt-2">Nesta fase, pagamentos são internos ou simulados e a modalidade operacional suportada é retirada presencial.</p></section></>}</Card></div></main>;
}
