import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';

import { AppHeader } from '../components/AppHeader';
import { Card } from '../components/ui';
import { listMyOrders } from '../services';
import type { CustomerOrder } from '../types';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const labels: Record<string, string> = { draft: 'Criado', 'Awaiting Payment': 'Aguardando pagamento', paid: 'Pago', preparing: 'Em preparo', ready_for_pickup: 'Pronto para retirada', completed: 'Concluído', in_transit: 'Em entrega' };
export function OrderDetailPage(): React.JSX.Element {
  const { orderId } = useParams(); const [order, setOrder] = useState<CustomerOrder | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { void listMyOrders().then((orders) => { const found = orders.find((item) => item.id === orderId); if (found) setOrder(found); else setError(true); }).catch(() => setError(true)).finally(() => setLoading(false)); }, [orderId]);
  return <main className="min-h-screen bg-[#fff1d6]"><AppHeader /><div className="mx-auto max-w-3xl px-5 py-9 sm:px-8"><Link to="/pedidos" className="text-sm font-bold text-ilarica-orange">← Meus pedidos</Link>{loading && <Card className="mt-6 p-10 text-center">Carregando pedido...</Card>}{error && <Card role="alert" className="mt-6 p-8 text-center"><h1 className="font-display text-2xl font-bold text-[#7a1e1e]">Pedido não encontrado</h1><p className="mt-2 text-sm text-ilarica-muted">Ele pode não existir ou não pertencer à sua conta.</p></Card>}{order && <><div className="mt-6 flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold text-ilarica-orange">Pedido #{order.id.slice(0, 8)}</p><h1 className="font-display text-3xl font-extrabold text-[#7a1e1e]">{order.canteen.name}</h1><p className="text-ilarica-muted">{order.canteen.location}</p></div><span className="h-fit rounded-full bg-[#fff0e8] px-4 py-2 text-sm font-bold text-ilarica-orange">{labels[order.status] ?? order.status}</span></div><Card className="mt-6 border-0 p-6 shadow-none"><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Itens</h2><ul className="mt-4 divide-y divide-ilarica-line">{order.items.map((item) => <li key={item.id} className="flex justify-between gap-4 py-3"><span>{item.quantity}x {item.name}</span><strong>{money.format(Number(item.unit_price) * item.quantity)}</strong></li>)}</ul><div className="mt-4 flex justify-between border-t border-ilarica-line pt-4 text-lg font-bold"><span>Total</span><span>{money.format(Number(order.total_amount))}</span></div></Card><Card className="mt-5 border-0 p-6 shadow-none"><h2 className="font-display text-xl font-bold text-[#7a1e1e]">Retirada</h2><p className="mt-2 text-sm text-ilarica-muted">{order.fulfillment_type === 'pickup' ? `Retire em ${order.canteen.location}.` : order.destination?.name}</p>{order.pickup_pin && <div className="mt-5 rounded-2xl bg-[#eff9f1] p-5 text-center text-[#237b39]"><span className="text-xs font-bold uppercase">PIN de retirada</span><strong className="block font-display text-4xl tracking-[0.3em]">{order.pickup_pin}</strong></div>}</Card></>}</div></main>;
}
