import { AppHeader } from '../components/AppHeader';
import { Card } from '../components/ui';
import { usePreferencesStore } from '../store';

function Switch({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }): React.JSX.Element { return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={onChange} className={`relative h-8 w-14 rounded-full ${checked ? 'bg-[#26a146]' : 'bg-[#929ca6]'}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white transition ${checked ? 'left-7' : 'left-1'}`} /></button>; }
export function PreferencesPage(): React.JSX.Element {
  const orderUpdates = usePreferencesStore((state) => state.orderUpdates); const pickupReady = usePreferencesStore((state) => state.pickupReady); const setPreference = usePreferencesStore((state) => state.setPreference);
  return <main className="min-h-screen bg-[#fff1d6]"><AppHeader /><div className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><h1 className="font-display text-3xl font-extrabold text-[#7a1e1e]">Preferências de notificação</h1><p className="mt-2 text-ilarica-muted">Escolha quais avisos operacionais deseja receber no aplicativo.</p><Card className="mt-7 divide-y divide-ilarica-line border-0 p-6 shadow-none"><div className="flex items-center justify-between gap-5 pb-5"><div><strong>Atualizações do pedido</strong><p className="mt-1 text-sm text-ilarica-muted">Mudanças de pagamento e preparo.</p></div><Switch label="Atualizações do pedido" checked={orderUpdates} onChange={() => setPreference('orderUpdates', !orderUpdates)} /></div><div className="flex items-center justify-between gap-5 pt-5"><div><strong>Pedido pronto</strong><p className="mt-1 text-sm text-ilarica-muted">Aviso quando puder retirar no balcão.</p></div><Switch label="Pedido pronto para retirada" checked={pickupReady} onChange={() => setPreference('pickupReady', !pickupReady)} /></div></Card><p role="status" className="mt-5 text-sm text-ilarica-muted">As preferências são salvas neste dispositivo durante o piloto.</p></div></main>;
}
